//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scaffoding.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SessionAttendance
    {
        public int uuid { get; set; }
        public string arrivalTime { get; set; }
        public Nullable<int> attendeeId { get; set; }
        public Nullable<int> sessionId { get; set; }
        public string comment { get; set; }
    
        public virtual Attendee Attendee { get; set; }
        public virtual SessionTb SessionTb { get; set; }
    }
}
