//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventRegistration
    {
        public int uuID { get; set; }
        public Nullable<int> eventID { get; set; }
        public Nullable<int> AttendeeID { get; set; }
    
        public virtual Attendee Attendee { get; set; }
        public virtual EventDetail EventDetail { get; set; }
    }
}
